
[font]
size = 8.5

[font.normal]
family = "PragmataPro Nerd Font"
#family = "PragmataPro"
#family = "monospace"

[font.bold]
style = "Regular"

[scrolling]
history = 10000

[window]

[general]
import = [
    "~/.config/alacritty/themes/themes/solarized_osaka.toml"
]
# option_as_alt = "Both"
